// src/lib/content/kashmir.ts
// Curated launch content for the Kashmir destination. Seeded idempotently by
// ensureContent() — only inserted if the destination has no itinerary yet.

export const KASHMIR = {
  stays: [
    { name: 'Houseboat New Beauty Group', type: 'HOMESTAY', neighbourhood: 'Dal Lake', pricePerNightINR: 4500, priceMonthlyINR: 90000, wifiRating: 3, hasCoworking: false, hasPowerBackup: true, viewType: 'Dal Lake & Zabarwan range', breakfastIncl: true, available: true, description: 'A classic carved-cedar houseboat on Dal Lake — wood-panelled rooms, a sit-out deck over the water and shikara service to shore. Quintessential Srinagar.', highlights: ['Lake View', 'Breakfast Included', 'Shikara service', 'Heritage'] },
    { name: 'The Lalit Grand Palace Srinagar', type: 'HOTEL', neighbourhood: 'Gupkar Road', pricePerNightINR: 12000, priceMonthlyINR: 240000, wifiRating: 5, hasCoworking: true, hasPowerBackup: true, viewType: 'Dal Lake & gardens', breakfastIncl: true, available: true, bookingUrl: 'https://www.thelalit.com/the-lalit-grand-palace-srinagar/', description: 'A former maharaja’s palace in 15 acres of gardens above Dal Lake. Reliable fibre, business centre and serious comfort for a focused work week.', highlights: ['Great WiFi', 'Business Centre', 'Lake View', 'Gardens'] },
    { name: 'Hotel Heevan Srinagar', type: 'HOTEL', neighbourhood: 'Boulevard Road', pricePerNightINR: 5500, priceMonthlyINR: 110000, wifiRating: 4, hasCoworking: false, hasPowerBackup: true, viewType: 'Dal Lake', breakfastIncl: true, available: true, description: 'Comfortable lakeside hotel right on the Boulevard — easy walk to shikara ghats, decent WiFi and balconies facing the water.', highlights: ['Lake View', 'Central', 'Good WiFi', 'Breakfast Included'] },
    { name: 'Welcomhotel by ITC, Pine-n-Peak Pahalgam', type: 'HOTEL', neighbourhood: 'Pahalgam', pricePerNightINR: 9000, wifiRating: 3, hasCoworking: false, hasPowerBackup: true, viewType: 'Lidder valley & pines', breakfastIncl: true, available: true, description: 'Pine-wrapped resort above the Lidder River in Pahalgam — the place to base a couple of mountain days away from Srinagar.', highlights: ['Mountain View', 'Riverside', 'Quiet', 'Breakfast Included'] },
    { name: 'Hotel Highlands Park, Gulmarg', type: 'HOTEL', neighbourhood: 'Gulmarg', pricePerNightINR: 8000, wifiRating: 2, hasCoworking: false, hasPowerBackup: true, viewType: 'Meadow & Apharwat', breakfastIncl: true, available: true, description: 'Old-world log-cabin charm in the Gulmarg meadow, near the Gondola. Patchy WiFi — a weekend escape rather than a work base.', highlights: ['Meadow View', 'Near Gondola', 'Cosy', 'Fireplaces'] },
  ],
  food: [
    { name: 'Ahdoos Restaurant', type: 'RESTAURANT', neighbourhood: 'Residency Road', description: 'A Srinagar institution since 1918 for authentic Wazwan. The place to try a proper Rogan Josh and Gushtaba.', mustOrder: ['Rogan Josh', 'Gushtaba', 'Mutton Yakhni', 'Kashmiri pulao'], wifiAvailable: false, laptopFriendly: false, avgBudgetINR: 700, openNow: true, seasonal: false, tags: ['Wazwan', 'Heritage', 'Authentic'] },
    { name: 'Mughal Darbar', type: 'RESTAURANT', neighbourhood: 'Residency Road', description: 'Beloved old-school Kashmiri restaurant — generous Wazwan platters and rista in a rich gravy.', mustOrder: ['Rista', 'Tabak Maaz', 'Mutton Rogan Josh'], wifiAvailable: false, laptopFriendly: false, avgBudgetINR: 650, openNow: true, seasonal: false, tags: ['Wazwan', 'Local Favourite'] },
    { name: 'Chai Jaai', type: 'CAFE', neighbourhood: 'Zaina Kadal (riverfront)', description: 'A restored riverfront house serving Kashmiri kahwa, noon chai and snacks with views over the Jhelum. Calm spot for a work coffee.', mustOrder: ['Kahwa', 'Noon chai', 'Walnut cake', 'Harissa (seasonal)'], wifiAvailable: true, laptopFriendly: true, avgBudgetINR: 400, openNow: true, seasonal: false, tags: ['Kahwa', 'River View', 'Work-Friendly'] },
    { name: 'Books & Bricks Café', type: 'CAFE', neighbourhood: 'Rajbagh', description: 'Quiet café-bookshop with good coffee, fast-ish WiFi and plug points — the closest thing Srinagar has to a co-working café.', mustOrder: ['Cappuccino', 'Sandwiches', 'Cheesecake'], wifiAvailable: true, laptopFriendly: true, avgBudgetINR: 450, openNow: true, seasonal: false, tags: ['Work-Friendly', 'Quiet', 'Coffee'] },
    { name: 'Krishna Dhaba', type: 'DHABA', neighbourhood: 'Durganag', description: 'Famous vegetarian dhaba — a reliable break from meat-heavy Wazwan. Rajma-chawal and paneer done right.', mustOrder: ['Rajma chawal', 'Paneer butter masala', 'Lassi'], wifiAvailable: false, laptopFriendly: false, avgBudgetINR: 300, openNow: true, seasonal: false, tags: ['Vegetarian', 'Comfort Food'] },
    { name: 'Lhasa Restaurant', type: 'RESTAURANT', neighbourhood: 'Boulevard / Sonwar', description: 'Long-running spot for Tibetan and Kashmiri dishes in a leafy garden — momos, thukpa and a quiet evening.', mustOrder: ['Mutton momos', 'Thukpa', 'Kashmiri pulao'], wifiAvailable: false, laptopFriendly: false, avgBudgetINR: 550, openNow: true, seasonal: false, tags: ['Garden', 'Tibetan'] },
  ],
  treks: [
    { name: 'Kashmir Great Lakes Trek (taster section)', difficulty: 'HARD', durationDays: 2, maxAltitudeM: 3800, distanceKm: 22, startPoint: 'Sonamarg', permitRequired: false, priceINR: 6500, company: 'Local guides, Sonamarg', available: true, season: 'July–September', description: 'A two-day taste of India’s most beautiful alpine-lakes trek — Nichnai meadows toward Vishansar. Wildflowers, shepherd camps and glacial lakes.', highlights: ['Vishansar Lake', 'Nichnai meadow', 'Alpine flowers', 'Shepherd trails'] },
    { name: 'Aru to Lidderwat', difficulty: 'MEDIUM', durationDays: 2, maxAltitudeM: 3000, distanceKm: 13, startPoint: 'Aru (Pahalgam)', permitRequired: false, priceINR: 4500, company: 'Pahalgam guides', available: true, season: 'May–September', description: 'Gentle pine-and-meadow walk from Aru village to the Lidderwat camping ground — a classic Pahalgam overnight beside the river.', highlights: ['Lidder River', 'Pine forest', 'Meadows', 'Village homestay'] },
    { name: 'Gulmarg to Khilanmarg', difficulty: 'EASY', durationDays: 1, maxAltitudeM: 3050, distanceKm: 6, startPoint: 'Gulmarg', permitRequired: false, priceINR: 2000, company: 'Gulmarg pony/guides', available: true, season: 'May–October', description: 'Short uphill meadow walk above Gulmarg to Khilanmarg, with a sweeping view of Nanga Parbat on a clear day.', highlights: ['Nanga Parbat view', 'Wildflower meadow', 'Easy half-day'] },
    { name: 'Tarsar Marsar (short loop)', difficulty: 'HARD', durationDays: 2, maxAltitudeM: 3990, distanceKm: 24, startPoint: 'Aru (Pahalgam)', permitRequired: false, priceINR: 7000, company: 'Local guides', available: true, season: 'July–September', description: 'Twin almond-shaped alpine lakes ringed by peaks — a stunning, less-crowded two-day section from the Aru side.', highlights: ['Tarsar Lake', 'Alpine camping', 'Reflections', 'Solitude'] },
  ],
  events: [
    { name: 'Tulip Festival', type: 'CULTURAL', location: 'Indira Gandhi Tulip Garden, Srinagar', startISO: '2026-04-01', endISO: '2026-04-15', ticketRequired: true, ticketPriceINR: 75, freeEntry: false, description: 'Asia’s largest tulip garden bursts into colour below the Zabarwan hills — over a million blooms with Dal Lake behind.', tips: 'Go early morning on a weekday; blooms peak early April.' },
    { name: 'Shikara Festival', type: 'CULTURAL', location: 'Dal Lake, Srinagar', startISO: '2026-07-18', endISO: '2026-07-20', ticketRequired: false, freeEntry: true, description: 'A lake carnival of decorated shikaras, dragon-boat races and cultural performances on and around Dal Lake.', tips: 'Watch from the Boulevard or hire a shikara for the races.' },
    { name: 'Gurez Festival', type: 'CULTURAL', location: 'Gurez Valley', startISO: '2026-08-08', endISO: '2026-08-09', ticketRequired: false, freeEntry: true, description: 'A celebration of remote Gurez — Dard-Shin culture, folk music and the dramatic Habba Khatoon peak.', tips: 'Permits/road status vary; check before the long drive.' },
    { name: 'Hazratbal Urs', type: 'FESTIVAL', location: 'Hazratbal Shrine, Srinagar', startISO: '2026-07-30', endISO: '2026-07-30', ticketRequired: false, freeEntry: true, description: 'Major commemoration at the white-marble Hazratbal shrine on Dal Lake’s western shore; large, devotional gatherings.', tips: 'Dress modestly; expect crowds and road closures nearby.' },
  ],
  transport: [
    { type: 'TAXI', destination: 'Gulmarg day trip', distanceKm: 50, rateINR: 3000, rateType: '1-day', permitRequired: false, permitTypes: [], durationHours: 1.5, notes: 'Return day trip from Srinagar; Gondola tickets extra.', available: true },
    { type: 'TAXI', destination: 'Pahalgam (one-way)', distanceKm: 90, rateINR: 3500, rateType: 'one-way', permitRequired: false, permitTypes: [], durationHours: 2.5, notes: 'Local Pahalgam union taxis required for Aru/Betaab/Chandanwari.', available: true },
    { type: 'TAXI', destination: 'Sonamarg day trip', distanceKm: 80, rateINR: 3500, rateType: '1-day', permitRequired: false, permitTypes: [], durationHours: 2.5, notes: 'Return day trip; ponies/local cabs for Thajiwas glacier extra.', available: true },
    { type: 'SHARED_JEEP', destination: 'Doodhpathri', distanceKm: 42, rateINR: 2500, rateType: '1-day', permitRequired: false, permitTypes: [], durationHours: 1.5, notes: 'Quiet meadow valley; less touristy alternative to Gulmarg.', available: true },
    { type: 'TAXI', destination: 'Srinagar airport transfer', distanceKm: 15, rateINR: 900, rateType: 'one-way', permitRequired: false, permitTypes: [], durationHours: 0.6, notes: 'Prepaid taxis available at SXR.', available: true },
  ],
  shop: [
    { name: 'Pashmina (Kani / Sozni) shawl', area: 'Srinagar', category: 'Textiles', estPriceINR: 12000, whereToBuy: 'Government Arts Emporium, Residency Rd', priority: 'must', notes: 'Look for the GI mark; sozni hand-embroidery commands the price.' },
    { name: 'Kashmiri saffron (Pampore)', area: 'Pampore', category: 'Food', estPriceINR: 500, whereToBuy: 'Pampore saffron co-ops', priority: 'must', notes: 'Deep-red Mongra threads; buy sealed, dated packs.' },
    { name: 'Walnut-wood carving', area: 'Srinagar', category: 'Handicraft', estPriceINR: 3500, whereToBuy: 'Old City workshops', priority: 'nice', notes: 'Trays, boxes and panels in fragrant walnut.' },
    { name: 'Papier-mâché box', area: 'Srinagar', category: 'Handicraft', estPriceINR: 800, whereToBuy: 'Downtown ateliers', priority: 'nice', notes: 'Hand-painted lacquered boxes and baubles.' },
    { name: 'Kashmiri kahwa & spice mix', area: 'Srinagar', category: 'Food', estPriceINR: 400, whereToBuy: 'Spice shops, Lal Chowk', priority: 'nice', notes: 'Green tea with saffron, cardamom and almond.' },
    { name: 'Hand-knotted Kashmiri carpet', area: 'Srinagar', category: 'Textiles', estPriceINR: 25000, whereToBuy: 'Certified emporiums', priority: 'maybe', notes: 'Silk/wool; ask for the knot count and a GI certificate.' },
  ],
  // dayNumber, day-of-week, title, description, flags, coords
  itinerary: [
    { dayNumber: 1, dayOfWeek: 'Sat', title: 'Arrive Srinagar — Dal Lake & shikara', isWorkDay: false, isExcursionDay: true, description: 'Land at Srinagar, settle into a houseboat. Ease in with a slow sunset shikara ride across Dal Lake past floating gardens. Early night.', lunchNote: 'Houseboat lunch', dinnerNote: 'Ahdoos — first Wazwan', locationName: 'Srinagar', lat: 34.0837, lng: 74.7973, altitudeM: 1585 },
    { dayNumber: 2, dayOfWeek: 'Sun', title: 'Mughal Gardens & Old City', isWorkDay: false, isExcursionDay: true, description: 'Nishat and Shalimar Bagh in the morning, then the Old City — Jamia Masjid, Hari Parbat views and the bustling lanes. Kahwa break by the Jhelum.', lunchNote: 'Chai Jaai, riverfront', dinnerNote: 'Mughal Darbar', locationName: 'Srinagar', lat: 34.0837, lng: 74.7973, altitudeM: 1585 },
    { dayNumber: 3, dayOfWeek: 'Mon', title: 'Work day + Hazratbal', isWorkDay: true, isExcursionDay: true, description: 'First work morning from the hotel/café WiFi. Late afternoon visit to the white-marble Hazratbal shrine on the lake’s western shore at golden hour.', breakfastNote: 'Houseboat', lunchNote: 'Books & Bricks (work here)', dinnerNote: 'Lhasa Restaurant', locationName: 'Srinagar', lat: 34.0837, lng: 74.7973, altitudeM: 1585 },
    { dayNumber: 4, dayOfWeek: 'Tue', title: 'Gulmarg — Gondola & meadows', isWorkDay: false, isExcursionDay: true, description: 'Day trip to Gulmarg. Ride the Gondola (Phase 1–2) toward Apharwat, walk the Khilanmarg meadow and watch for Nanga Parbat. Back to Srinagar by evening.', lunchNote: 'Gulmarg meadow café', dinnerNote: 'Krishna Dhaba', locationName: 'Gulmarg', lat: 34.0498, lng: 74.38, altitudeM: 2650 },
    { dayNumber: 5, dayOfWeek: 'Wed', title: 'Deep work day, Srinagar', isWorkDay: true, description: 'Full focused work day from a lakeside café. Evening stroll on the Boulevard and a quiet shikara at dusk.', breakfastNote: 'Houseboat', lunchNote: 'Chai Jaai', dinnerNote: 'Ahdoos', locationName: 'Srinagar', lat: 34.0837, lng: 74.7973, altitudeM: 1585 },
    { dayNumber: 6, dayOfWeek: 'Thu', title: 'Work + drive to Pahalgam', isWorkDay: true, isExcursionDay: true, description: 'Half-day work, then drive to Pahalgam (90km). Check into a riverside resort; evening walk along the Lidder.', lunchNote: 'On the road', dinnerNote: 'Resort dining, Pahalgam', locationName: 'Pahalgam', lat: 34.0161, lng: 75.315, altitudeM: 2740 },
    { dayNumber: 7, dayOfWeek: 'Fri', title: 'Aru & Betaab Valley', isWorkDay: false, isExcursionDay: true, description: 'Local taxi to Aru and Betaab Valley — meadows, the Lidder river and pine slopes. Optional short hike toward Lidderwat. Return to Pahalgam.', lunchNote: 'Aru village dhaba', dinnerNote: 'Pahalgam', locationName: 'Pahalgam', lat: 34.0161, lng: 75.315, altitudeM: 2740 },
    { dayNumber: 8, dayOfWeek: 'Sat', title: 'Back to Srinagar + work', isWorkDay: true, isExcursionDay: true, description: 'Morning drive back to Srinagar. Afternoon work session. Evening at the Polo View / Lal Chowk markets.', lunchNote: 'On the road', dinnerNote: 'Mughal Darbar', locationName: 'Srinagar', lat: 34.0837, lng: 74.7973, altitudeM: 1585 },
    { dayNumber: 9, dayOfWeek: 'Sun', title: 'Sonamarg — Thajiwas glacier', isWorkDay: false, isExcursionDay: true, description: 'Day trip to Sonamarg, the “meadow of gold”. Pony or walk to the Thajiwas glacier snout; alpine river views the whole drive.', lunchNote: 'Sonamarg dhaba', dinnerNote: 'Lhasa Restaurant', locationName: 'Sonamarg', lat: 34.303, lng: 75.292, altitudeM: 2800 },
    { dayNumber: 10, dayOfWeek: 'Mon', title: 'Doodhpathri & farewell', isWorkDay: false, isExcursionDay: true, description: 'A quiet final day in the Doodhpathri meadows away from the crowds, or a slow morning of last shopping for pashmina and saffron before departure.', lunchNote: 'Meadow picnic', dinnerNote: 'Airport / departure', locationName: 'Doodhpathri', lat: 33.84, lng: 74.85, altitudeM: 2730 },
  ],
} as const
