// src/lib/content/pokhara.ts
// Curated launch content for Pokhara (Nepal). Prices shown in the app's ₹ UI as
// approximate INR equivalents. Seeded idempotently by ensureContent().

export const POKHARA = {
  stays: [
    { name: 'Temple Tree Resort & Spa', type: 'HOTEL', neighbourhood: 'Lakeside (Gaurighat)', pricePerNightINR: 7000, priceMonthlyINR: 140000, wifiRating: 4, hasCoworking: false, hasPowerBackup: true, viewType: 'Garden & Phewa Lake', breakfastIncl: true, available: true, description: 'Calm Newari-style resort steps from Phewa Lake — leafy courtyards, a pool and reliable WiFi. A comfortable Lakeside work base.', highlights: ['Near Lake', 'Pool', 'Good WiFi', 'Breakfast Included'] },
    { name: 'Hotel Middle Path & Spa', type: 'HOTEL', neighbourhood: 'Lakeside', pricePerNightINR: 4500, priceMonthlyINR: 90000, wifiRating: 4, hasCoworking: false, hasPowerBackup: true, viewType: 'Mountain & garden', breakfastIncl: true, available: true, description: 'Central Lakeside hotel with a garden, rooftop Annapurna views and dependable internet — easy walk to every café.', highlights: ['Central', 'Rooftop View', 'Good WiFi'] },
    { name: 'Pavilions Himalayas The Farm', type: 'HOTEL', neighbourhood: 'Phewa (south shore)', pricePerNightINR: 11000, wifiRating: 3, hasCoworking: false, hasPowerBackup: true, viewType: 'Farm & Annapurna', breakfastIncl: true, available: true, description: 'Eco-resort villas on an organic farm across the lake — quiet, scenic and great for deep-focus weeks away from the strip.', highlights: ['Eco', 'Annapurna View', 'Quiet', 'Farm-to-table'] },
    { name: 'Hotel Lake Star', type: 'GUESTHOUSE', neighbourhood: 'Lakeside (Baidam)', pricePerNightINR: 2200, priceMonthlyINR: 45000, wifiRating: 3, hasCoworking: false, hasPowerBackup: true, viewType: 'Garden', breakfastIncl: false, available: true, description: 'Friendly budget guesthouse a lane back from the lake — clean rooms, rooftop and long-stay rates for workationers.', highlights: ['Budget', 'Long-stay rates', 'Rooftop'] },
    { name: 'Begnas Lake Resort', type: 'HOTEL', neighbourhood: 'Begnas Lake', pricePerNightINR: 6000, wifiRating: 2, hasCoworking: false, hasPowerBackup: true, viewType: 'Begnas Lake & forest', breakfastIncl: true, available: true, description: 'Hillside cottages over the quieter Begnas Lake, 30 min from town — birdsong, boating and zero crowds.', highlights: ['Lake View', 'Quiet', 'Nature'] },
  ],
  food: [
    { name: 'Caffe Concerto', type: 'RESTAURANT', neighbourhood: 'Lakeside', description: 'Lakeside favourite for wood-fired pizza and pasta with an Annapurna backdrop — busy, reliable, great sunsets.', mustOrder: ['Wood-fired pizza', 'Pasta', 'Tiramisu'], wifiAvailable: true, laptopFriendly: false, avgBudgetINR: 700, openNow: true, seasonal: false, tags: ['Italian', 'Lake View'] },
    { name: 'Am/Pm Organic Café', type: 'CAFE', neighbourhood: 'Lakeside', description: 'Bright organic café with strong coffee, big breakfasts, fast WiFi and plug points — the de-facto co-working café of Lakeside.', mustOrder: ['Flat white', 'Big breakfast', 'Smoothie bowl'], wifiAvailable: true, laptopFriendly: true, avgBudgetINR: 450, openNow: true, seasonal: false, tags: ['Work-Friendly', 'Coffee', 'Healthy'] },
    { name: 'Or2k Pokhara', type: 'RESTAURANT', neighbourhood: 'Lakeside', description: 'Cushioned floor-seating Middle-Eastern & veg spot — mezze, falafel and a mellow vibe for a long lunch.', mustOrder: ['Mezze platter', 'Falafel', 'Fresh juices'], wifiAvailable: true, laptopFriendly: true, avgBudgetINR: 500, openNow: true, seasonal: false, tags: ['Vegetarian', 'Relaxed', 'Work-Friendly'] },
    { name: 'Krishna’s Kitchen', type: 'RESTAURANT', neighbourhood: 'Lakeside', description: 'Long-running spot for authentic Nepali dal bhat and thakali sets — refuel after a hike.', mustOrder: ['Thakali dal bhat', 'Momo', 'Gundruk'], wifiAvailable: false, laptopFriendly: false, avgBudgetINR: 350, openNow: true, seasonal: false, tags: ['Nepali', 'Dal Bhat', 'Value'] },
    { name: 'Pokhara Thakali Kitchen', type: 'RESTAURANT', neighbourhood: 'Lakeside', description: 'Classic Thakali thali from the Annapurna region — buckwheat, ghee and slow-cooked dal.', mustOrder: ['Thakali set', 'Buckwheat roti', 'Local chicken'], wifiAvailable: false, laptopFriendly: false, avgBudgetINR: 400, openNow: true, seasonal: false, tags: ['Nepali', 'Thakali'] },
    { name: 'Movie Garden / German Bakery', type: 'BAKERY', neighbourhood: 'Lakeside', description: 'Garden bakery for fresh croissants, apple pie and espresso — easy morning work spot before the heat.', mustOrder: ['Croissant', 'Apple pie', 'Cinnamon roll'], wifiAvailable: true, laptopFriendly: true, avgBudgetINR: 350, openNow: true, seasonal: false, tags: ['Bakery', 'Coffee', 'Garden'] },
  ],
  treks: [
    { name: 'Sarangkot Sunrise Walk', difficulty: 'EASY', durationDays: 1, maxAltitudeM: 1592, distanceKm: 5, startPoint: 'Pokhara', permitRequired: false, priceINR: 1200, company: 'Local guides', available: true, season: 'All year', description: 'Pre-dawn drive/walk up to Sarangkot for the Annapurna and Machhapuchhre sunrise, then an easy descent to town.', highlights: ['Annapurna sunrise', 'Fishtail view', 'Paragliding launch'] },
    { name: 'Australian Camp via Dhampus', difficulty: 'EASY', durationDays: 2, maxAltitudeM: 2060, distanceKm: 12, startPoint: 'Kande', permitRequired: true, priceINR: 4000, company: 'Annapurna trekking agencies', available: true, season: 'Sep–May', description: 'A gentle two-day intro to Annapurna foothills — terraced villages, rhododendron forest and a ridge-top camp facing the giants.', highlights: ['Dhampus village', 'Ridge sunrise', 'Forest trail', 'Homestay'] },
    { name: 'Poon Hill (short itinerary)', difficulty: 'MEDIUM', durationDays: 2, maxAltitudeM: 3210, distanceKm: 22, startPoint: 'Nayapul / Ulleri', permitRequired: true, priceINR: 8000, company: 'ACAP-registered agencies', available: true, season: 'Oct–Apr', description: 'The famous Poon Hill panorama condensed — stone-step villages to a sunrise over Dhaulagiri and the Annapurnas.', highlights: ['Ghorepani', 'Poon Hill sunrise', 'Dhaulagiri', 'Magar villages'] },
    { name: 'Mardi Himal Base (taster)', difficulty: 'HARD', durationDays: 2, maxAltitudeM: 3550, distanceKm: 20, startPoint: 'Kande', permitRequired: true, priceINR: 9000, company: 'ACAP agencies', available: true, season: 'Oct–Apr', description: 'A steeper forest-and-ridge climb toward the Mardi Himal high camp under the Fishtail — fewer crowds, huge views.', highlights: ['Forest camp', 'Fishtail close-up', 'Ridge walking'] },
  ],
  events: [
    { name: 'Fewa Festival (Pokhara Street Festival)', type: 'CULTURAL', location: 'Lakeside, Pokhara', startISO: '2026-12-28', endISO: '2027-01-01', ticketRequired: false, freeEntry: true, description: 'Lakeside’s biggest party — food stalls, live music and street performances seeing in the new year along the Phewa shore.', tips: 'Book Lakeside stays well ahead for late December.' },
    { name: 'Dashain', type: 'FESTIVAL', location: 'Across Pokhara', startISO: '2026-10-11', endISO: '2026-10-23', ticketRequired: false, freeEntry: true, description: 'Nepal’s grandest festival — family gatherings, swings (ping), kites and tika. Shops shut but the city is joyful.', tips: 'Some businesses close; plan food and transport around the main days.' },
    { name: 'Tihar (Festival of Lights)', type: 'FESTIVAL', location: 'Across Pokhara', startISO: '2026-11-09', endISO: '2026-11-13', ticketRequired: false, freeEntry: true, description: 'Lamps, marigold garlands and Deusi-Bhailo singing light up the lanes; Lakeside glows in the evenings.', tips: 'Evenings are the magic hour — wander the decorated streets.' },
    { name: 'Maghe Sankranti at Devi’s Fall', type: 'CULTURAL', location: 'Devi’s Fall / Gupteshwor, Pokhara', startISO: '2027-01-15', endISO: '2027-01-15', ticketRequired: false, freeEntry: true, description: 'Mid-winter festival with ritual bathing and sweet treats (til, ghee, sweet potato) at sacred spots around town.', tips: 'Pair with the Gupteshwor cave next door.' },
  ],
  transport: [
    { type: 'TAXI', destination: 'Sarangkot sunrise (return)', distanceKm: 12, rateINR: 1500, rateType: 'one-way', permitRequired: false, permitTypes: [], durationHours: 0.7, notes: 'Pre-dawn pickup for sunrise; arrange the night before.', available: true },
    { type: 'TAXI', destination: 'World Peace Pagoda', distanceKm: 8, rateINR: 1200, rateType: 'one-way', permitRequired: false, permitTypes: [], durationHours: 0.5, notes: 'Or boat across Phewa + 30-min hike up.', available: true },
    { type: 'SHARED_JEEP', destination: 'Begnas Lake', distanceKm: 15, rateINR: 1000, rateType: 'one-way', permitRequired: false, permitTypes: [], durationHours: 0.6, notes: 'Quieter lake; boating and lakeside cafés.', available: true },
    { type: 'TAXI', destination: 'Kande (trailhead)', distanceKm: 28, rateINR: 2200, rateType: 'one-way', permitRequired: false, permitTypes: [], durationHours: 1.0, notes: 'Start point for Australian Camp / Mardi Himal.', available: true },
    { type: 'BIKE_RENTAL', destination: 'Scooter day rental', distanceKm: 0, rateINR: 800, rateType: 'per-day', permitRequired: false, permitTypes: [], notes: 'Easy way to reach Begnas, Devi’s Fall and viewpoints.', available: true },
  ],
  shop: [
    { name: 'Tibetan singing bowl', area: 'Lakeside', category: 'Spiritual', estPriceINR: 2000, whereToBuy: 'Tibetan stalls, Lakeside', priority: 'must', notes: 'Hand-hammered; test the tone and sustain before buying.' },
    { name: 'Pashmina shawl', area: 'Lakeside', category: 'Textiles', estPriceINR: 3500, whereToBuy: 'Lakeside shops', priority: 'nice', notes: 'Plenty of blends — feel the weight for genuine pashmina.' },
    { name: 'Khukuri (Gurkha knife)', area: 'Lakeside', category: 'Handicraft', estPriceINR: 2500, whereToBuy: 'Khukuri houses, Lakeside', priority: 'maybe', notes: 'Check airline rules — must go in checked baggage.' },
    { name: 'Lokta paper journals', area: 'Lakeside', category: 'Handicraft', estPriceINR: 500, whereToBuy: 'Handmade-paper shops', priority: 'nice', notes: 'Handmade Himalayan bark paper — light and giftable.' },
    { name: 'Nepali tea (Ilam)', area: 'Lakeside', category: 'Food', estPriceINR: 400, whereToBuy: 'Tea shops, Lakeside', priority: 'nice', notes: 'Black/green high-grown leaf; buy sealed.' },
    { name: 'Felt wool slippers & toys', area: 'Lakeside', category: 'Textiles', estPriceINR: 600, whereToBuy: 'Women’s co-op shops', priority: 'nice', notes: 'Handmade felt — colourful and packable.' },
  ],
  itinerary: [
    { dayNumber: 1, dayOfWeek: 'Sat', title: 'Arrive Pokhara — Lakeside & Phewa', isWorkDay: false, isExcursionDay: true, description: 'Settle into Lakeside. A sunset row across Phewa Lake to Tal Barahi temple, then a stroll along the lakeshore strip.', lunchNote: 'Caffe Concerto', dinnerNote: 'Or2k', locationName: 'Pokhara (Lakeside)', lat: 28.2096, lng: 83.9856, altitudeM: 820 },
    { dayNumber: 2, dayOfWeek: 'Sun', title: 'Sarangkot sunrise + World Peace Pagoda', isWorkDay: false, isExcursionDay: true, description: 'Pre-dawn to Sarangkot for the Annapurna sunrise. Later, boat across and hike to the World Peace Pagoda for lake panoramas.', lunchNote: 'Lakeside café', dinnerNote: 'Krishna’s Kitchen', locationName: 'Sarangkot', lat: 28.2438, lng: 83.949, altitudeM: 1592 },
    { dayNumber: 3, dayOfWeek: 'Mon', title: 'Work day + caves & falls', isWorkDay: true, isExcursionDay: true, description: 'Morning work from Am/Pm café. Late afternoon: Devi’s Fall and the Gupteshwor cave, then sunset on the lake.', breakfastNote: 'Movie Garden bakery', lunchNote: 'Am/Pm Organic (work here)', dinnerNote: 'Pokhara Thakali Kitchen', locationName: 'Pokhara (Lakeside)', lat: 28.2096, lng: 83.9856, altitudeM: 820 },
    { dayNumber: 4, dayOfWeek: 'Tue', title: 'Paragliding + work', isWorkDay: true, isExcursionDay: true, description: 'Tandem paragliding off Sarangkot over the lake in the morning thermals, then an afternoon work session back at the café.', lunchNote: 'Caffe Concerto', dinnerNote: 'Or2k', locationName: 'Sarangkot', lat: 28.2438, lng: 83.949, altitudeM: 1592 },
    { dayNumber: 5, dayOfWeek: 'Wed', title: 'Deep work day', isWorkDay: true, description: 'Full focused day from a lakeside café; evening lakeshore walk and an early night before the trek.', breakfastNote: 'German Bakery', lunchNote: 'Am/Pm Organic', dinnerNote: 'Krishna’s Kitchen', locationName: 'Pokhara (Lakeside)', lat: 28.2096, lng: 83.9856, altitudeM: 820 },
    { dayNumber: 6, dayOfWeek: 'Thu', title: 'Trek to Australian Camp', isWorkDay: false, isTrekDay: true, description: 'Drive to Kande and hike via Dhampus to Australian Camp — terraced fields, forest and a ridge facing the Annapurnas. Overnight on the ridge.', lunchNote: 'Trail teahouse', dinnerNote: 'Australian Camp lodge', locationName: 'Australian Camp', lat: 28.3, lng: 83.85, altitudeM: 2060 },
    { dayNumber: 7, dayOfWeek: 'Fri', title: 'Ridge sunrise → back to Pokhara', isWorkDay: false, isTrekDay: true, description: 'Sunrise over Machhapuchhre, descend through Dhampus and return to Lakeside by afternoon. Rest and recover.', breakfastNote: 'Camp lodge', lunchNote: 'On the trail', dinnerNote: 'Caffe Concerto', locationName: 'Australian Camp', lat: 28.3, lng: 83.85, altitudeM: 2060 },
    { dayNumber: 8, dayOfWeek: 'Sat', title: 'Begnas Lake escape', isWorkDay: false, isExcursionDay: true, description: 'Day at the quieter Begnas Lake — boating, a forest walk and a lazy lakeside lunch away from the crowds.', lunchNote: 'Begnas lakeside', dinnerNote: 'Pokhara Thakali Kitchen', locationName: 'Begnas Lake', lat: 28.17, lng: 84.09, altitudeM: 650 },
    { dayNumber: 9, dayOfWeek: 'Sun', title: 'Work + Old Bazaar & museums', isWorkDay: true, isExcursionDay: true, description: 'Work morning. Afternoon in Pokhara’s Old Bazaar, the Bindhyabasini temple and the International Mountain Museum.', lunchNote: 'Am/Pm Organic', dinnerNote: 'Or2k', locationName: 'Pokhara (Lakeside)', lat: 28.2096, lng: 83.9856, altitudeM: 820 },
    { dayNumber: 10, dayOfWeek: 'Mon', title: 'Slow morning & farewell', isWorkDay: false, isExcursionDay: true, description: 'A final lake row and last-minute shopping for singing bowls and lokta journals before departure.', lunchNote: 'Lakeside café', dinnerNote: 'Airport / departure', locationName: 'Pokhara (Lakeside)', lat: 28.2096, lng: 83.9856, altitudeM: 820 },
  ],
} as const
