// src/lib/content/sikkim.ts
// Curated launch content for the Sikkim destination. Seeded idempotently by
// ensureContent() — only inserted if the destination has no itinerary yet.

export const SIKKIM = {
  stays: [
    { name: 'Mayfair Spa Resort & Casino, Gangtok', type: 'HOTEL', neighbourhood: 'Ranipool, Gangtok', pricePerNightINR: 11000, priceMonthlyINR: 220000, wifiRating: 5, hasCoworking: true, hasPowerBackup: true, viewType: 'Forested hills & valley', breakfastIncl: true, available: true, bookingUrl: 'https://www.mayfairhotels.com/mayfair-gangtok/', description: 'Sprawling hillside resort wrapped in cardamom forest just below Gangtok. Reliable fibre, a business centre and a spa — the most comfortable base for a focused work week.', highlights: ['Great WiFi', 'Business Centre', 'Spa', 'Breakfast Included'] },
    { name: 'The Elgin Nor-Khill, Gangtok', type: 'HOTEL', neighbourhood: 'Stadium Road, Gangtok', pricePerNightINR: 9000, priceMonthlyINR: 180000, wifiRating: 4, hasCoworking: false, hasPowerBackup: true, viewType: 'Garden & ridge', breakfastIncl: true, available: true, description: 'A 1930s royal guest house turned heritage hotel — wood-panelled rooms, manicured gardens and old-Sikkim charm a short walk from MG Marg.', highlights: ['Heritage', 'Central', 'Garden', 'Breakfast Included'] },
    { name: 'WelcomHeritage Denzong Regency', type: 'HOTEL', neighbourhood: 'Upper Sichey, Gangtok', pricePerNightINR: 7000, priceMonthlyINR: 140000, wifiRating: 4, hasCoworking: false, hasPowerBackup: true, viewType: 'Kanchenjunga (clear days)', breakfastIncl: true, available: true, description: 'Quiet ridge-top hotel with Kanchenjunga views on a clear morning, good WiFi and balconies — calm enough for deep-work days away from the bazaar.', highlights: ['Mountain View', 'Quiet', 'Good WiFi', 'Breakfast Included'] },
    { name: 'Hotel Sonam Delek, Gangtok', type: 'GUESTHOUSE', neighbourhood: 'Tibet Road, Gangtok', pricePerNightINR: 3500, priceMonthlyINR: 70000, wifiRating: 3, hasCoworking: false, hasPowerBackup: true, viewType: 'Valley & garden', breakfastIncl: true, available: true, description: 'Long-running family-run hotel a minute from MG Marg with a pretty garden terrace, honest food and friendly owners. Best value central base.', highlights: ['Central', 'Garden', 'Value', 'Breakfast Included'] },
    { name: 'The Chumbi Mountain Retreat, Pelling', type: 'HOTEL', neighbourhood: 'Pelling (West Sikkim)', pricePerNightINR: 8000, wifiRating: 3, hasCoworking: false, hasPowerBackup: true, viewType: 'Kanchenjunga & pine valley', breakfastIncl: true, available: true, description: 'Boutique cottages with a full-frontal Kanchenjunga view at sunrise — the place to base a couple of West-Sikkim days around Pemayangtse and Khecheopalri.', highlights: ['Kanchenjunga View', 'Cottages', 'Quiet', 'Breakfast Included'] },
  ],
  food: [
    { name: 'Nimtho', type: 'RESTAURANT', neighbourhood: 'Tibet Road, Gangtok', description: 'The place for authentic Sikkimese cooking — gundruk, phagshapa, kinema and millet tongba served in a warm wood-lined room. Start here to understand the local plate.', mustOrder: ['Phagshapa', 'Gundruk soup', 'Sha phaley', 'Tongba (millet beer)'], wifiAvailable: false, laptopFriendly: false, avgBudgetINR: 600, openNow: true, seasonal: false, tags: ['Sikkimese', 'Authentic', 'Local'] },
    { name: 'Taste of Tibet', type: 'RESTAURANT', neighbourhood: 'MG Marg, Gangtok', description: 'A Gangtok institution for steaming momos and thukpa right on the pedestrian mall. Always busy, always good — the go-to comfort lunch.', mustOrder: ['Pork momos', 'Thenthuk', 'Gyathuk', 'Beef chilli'], wifiAvailable: false, laptopFriendly: false, avgBudgetINR: 350, openNow: true, seasonal: false, tags: ['Momos', 'Tibetan', 'Local Favourite'] },
    { name: 'Baker’s Café', type: 'CAFE', neighbourhood: 'MG Marg, Gangtok', description: 'Bright two-storey café on MG Marg with proper coffee, a bakery counter, plug points and decent WiFi — the most reliable work-from-café spot in town.', mustOrder: ['Cappuccino', 'Wood-fired pizza', 'Cinnamon roll', 'Cold coffee'], wifiAvailable: true, laptopFriendly: true, avgBudgetINR: 450, openNow: true, seasonal: false, tags: ['Work-Friendly', 'Coffee', 'Bakery'] },
    { name: 'Café Live & Loud', type: 'CAFE', neighbourhood: 'MG Marg, Gangtok', description: 'Relaxed music café with sofas, good espresso and a balcony over the mall. Quiet enough by day for a long work session, live music by night.', mustOrder: ['Americano', 'Burger', 'Nachos', 'Lemon iced tea'], wifiAvailable: true, laptopFriendly: true, avgBudgetINR: 500, openNow: true, seasonal: false, tags: ['Work-Friendly', 'Music', 'Coffee'] },
    { name: 'The Coffee Shop by Golden Tips', type: 'CAFE', neighbourhood: 'MG Marg, Gangtok', description: 'Tea-and-coffee bar to sample Sikkim’s own Temi tea and Himalayan brews, with cake and a calm corner to read or plan the next day.', mustOrder: ['Temi tea', 'Masala chai', 'Walnut cake'], wifiAvailable: true, laptopFriendly: true, avgBudgetINR: 300, openNow: true, seasonal: false, tags: ['Temi Tea', 'Quiet', 'Work-Friendly'] },
    { name: 'Roll House', type: 'STREET_FOOD', neighbourhood: 'MG Marg / Lal Bazaar, Gangtok', description: 'Beloved quick-bite counter for hot egg-and-chicken rolls and crisp momos — the local after-work street snack. Cheap, fast and very good.', mustOrder: ['Double egg chicken roll', 'Fried momos', 'Aloo roll'], wifiAvailable: false, laptopFriendly: false, avgBudgetINR: 150, openNow: true, seasonal: false, tags: ['Street Food', 'Budget', 'Quick'] },
  ],
  treks: [
    { name: 'Dzongri Trek (Goecha La taster)', difficulty: 'HARD', durationDays: 2, maxAltitudeM: 4200, distanceKm: 24, startPoint: 'Yuksom (West Sikkim)', permitRequired: true, priceINR: 8500, company: 'Yuksom-registered operators', available: true, season: 'April–May & October–November', description: 'The classic climb from Yuksom through rhododendron and silver-fir forest to the Dzongri meadows, with a dawn panorama of Kanchenjunga and Pandim. A two-day section of the famous Goecha La route.', highlights: ['Kanchenjunga sunrise', 'Dzongri Top', 'Rhododendron forest', 'High meadows'] },
    { name: 'Khecheopalri & Yuksom Heritage Walk', difficulty: 'EASY', durationDays: 1, maxAltitudeM: 1950, distanceKm: 8, startPoint: 'Pelling / Khecheopalri', permitRequired: false, priceINR: 2500, company: 'Local guides, Pelling', available: true, season: 'March–November', description: 'A gentle forest walk around the sacred wish-fulfilling Khecheopalri Lake and into Yuksom, Sikkim’s first capital, taking in the Norbugang coronation throne. Birdsong, prayer flags and still water.', highlights: ['Sacred lake', 'Coronation throne', 'Forest birds', 'First capital'] },
    { name: 'Barsey Rhododendron Trek', difficulty: 'MEDIUM', durationDays: 2, maxAltitudeM: 3050, distanceKm: 14, startPoint: 'Hilley (West Sikkim)', permitRequired: false, priceINR: 4500, company: 'Local guides, Hilley/Sombaria', available: true, season: 'March–May & October', description: 'A short forest trek through the Barsey Rhododendron Sanctuary to a ridge with sweeping Singalila and Kanchenjunga views — spectacular when the rhododendrons bloom in spring.', highlights: ['Rhododendron blooms', 'Singalila views', 'Ridge camp', 'Quiet trail'] },
    { name: 'Maenam Hill Trek (Ravangla)', difficulty: 'MEDIUM', durationDays: 1, maxAltitudeM: 3260, distanceKm: 12, startPoint: 'Ravangla (South Sikkim)', permitRequired: false, priceINR: 3000, company: 'Ravangla guides', available: true, season: 'March–November', description: 'A steady forest climb from Ravangla through the Maenam Wildlife Sanctuary to a summit viewpoint over the Teesta valley and the Kanchenjunga range — pair it with the Buddha Park below.', highlights: ['Summit viewpoint', 'Wildlife sanctuary', 'Teesta valley', 'Buddha Park nearby'] },
  ],
  events: [
    { name: 'Saga Dawa', type: 'FESTIVAL', location: 'Monasteries statewide (Gangtok, Tsuklakhang)', startISO: '2026-05-31', endISO: '2026-05-31', ticketRequired: false, freeEntry: true, description: 'The holiest Buddhist day in Sikkim, marking the Buddha’s birth, enlightenment and parinirvana. Lamas lead processions carrying scriptures through Gangtok and butter-lamps fill the monasteries.', tips: 'Join the morning procession near Tsuklakhang; dress modestly and follow the crowd clockwise.' },
    { name: 'Pang Lhabsol', type: 'FESTIVAL', location: 'Tsuklakhang & monasteries, Gangtok', startISO: '2026-08-27', endISO: '2026-08-27', ticketRequired: false, freeEntry: true, description: 'A uniquely Sikkimese festival honouring Mount Kanchenjunga as the state’s guardian deity, with dramatic warrior Cham dances and the masked Pangtoed dance.', tips: 'The Tsuklakhang palace monastery in Gangtok hosts the best masked dances — arrive early.' },
    { name: 'Bumchu Festival', type: 'FESTIVAL', location: 'Tashiding Monastery, West Sikkim', startISO: '2026-03-03', endISO: '2026-03-04', ticketRequired: false, freeEntry: true, description: 'A sacred-water ceremony at hilltop Tashiding Monastery, where a holy pot is opened once a year and its level read as an omen for the year ahead.', tips: 'A long drive from Gangtok; combine with a Pelling/West-Sikkim loop.' },
    { name: 'Losoong / Namsoong', type: 'FESTIVAL', location: 'Statewide (Rumtek, Lingdum)', startISO: '2026-12-09', endISO: '2026-12-11', ticketRequired: false, freeEntry: true, description: 'The Sikkimese harvest and new-year festival of the Bhutia and Lepcha communities, marked by Cham dances at monasteries like Rumtek and lively local fairs.', tips: 'Rumtek and Lingdum (Ranka) host the most accessible Cham dances.' },
  ],
  transport: [
    { type: 'SHARED_JEEP', destination: 'Tsomgo Lake & Baba Mandir (with permit)', distanceKm: 40, rateINR: 4500, rateType: '1-day', permitRequired: true, permitTypes: ['Protected Area Permit'], durationHours: 2, notes: 'Reserved shared Sumo from MG Marg; permit arranged by the operator a day ahead. Nathula add-on extra.', available: true },
    { type: 'SHARED_JEEP', destination: 'Gangtok ↔ Pelling', distanceKm: 115, rateINR: 350, rateType: 'one-way', permitRequired: false, permitTypes: [], durationHours: 4.5, notes: 'Shared Sumo seat from the private taxi stand; reserve the whole vehicle (~₹4,500) for comfort.', available: true },
    { type: 'SHARED_JEEP', destination: 'Gangtok ↔ Lachung (North Sikkim, with permit)', distanceKm: 110, rateINR: 6000, rateType: 'one-way', permitRequired: true, permitTypes: ['Protected Area Permit'], durationHours: 6, notes: 'North-Sikkim runs are package-based via registered operators; Yumthang Valley needs the permit.', available: true },
    { type: 'TAXI', destination: 'Pakyong Airport (PYG) transfer', distanceKm: 30, rateINR: 1200, rateType: 'one-way', permitRequired: false, permitTypes: [], durationHours: 1.2, notes: 'Bagdogra (IXB) is the bigger hub ~4hr away if no Pakyong flight suits.', available: true },
    { type: 'TAXI', destination: 'Gangtok local sightseeing (Rumtek/Enchey/viewpoints)', distanceKm: 45, rateINR: 2500, rateType: '1-day', permitRequired: false, permitTypes: [], durationHours: 5, notes: 'Half- or full-day local circuit; MG Marg itself is pedestrian-only.', available: true },
  ],
  shop: [
    { name: 'Temi tea (Sikkim’s own estate)', area: 'Gangtok', category: 'Food', estPriceINR: 600, whereToBuy: 'Golden Tips / Temi Tea outlets, MG Marg', priority: 'must', notes: 'The state’s single tea garden — buy sealed first-flush black or green packs.' },
    { name: 'Large cardamom (badi elaichi)', area: 'Gangtok', category: 'Food', estPriceINR: 700, whereToBuy: 'Lal Bazaar spice stalls', priority: 'must', notes: 'Sikkim is India’s biggest grower; smoky, fragrant pods sold by weight.' },
    { name: 'Carved Choktse folding table', area: 'Gangtok', category: 'Handicraft', estPriceINR: 4500, whereToBuy: 'Directorate of Handicrafts & Handloom, Zero Point', priority: 'nice', notes: 'Traditional hand-carved low table; smaller pieces pack down well.' },
    { name: 'Thangka painting', area: 'Gangtok', category: 'Handicraft', estPriceINR: 5000, whereToBuy: 'Handicrafts emporium & monastery shops', priority: 'nice', notes: 'Hand-painted Buddhist scroll; ask about the school and pigments.' },
    { name: 'Dalle khursani chilli pickle', area: 'Gangtok', category: 'Food', estPriceINR: 250, whereToBuy: 'Organic & local-produce shops, MG Marg', priority: 'nice', notes: 'Fiery round Himalayan chilli — Sikkim is a fully organic state, so look for the organic mark.' },
    { name: 'Lepcha hand-woven carpet / shawl', area: 'Gangtok', category: 'Textiles', estPriceINR: 8000, whereToBuy: 'Directorate of Handicrafts & Handloom', priority: 'maybe', notes: 'Wool carpets and weaves with traditional Lepcha and Bhutia motifs.' },
  ],
  // dayNumber, day-of-week, title, description, flags, coords
  itinerary: [
    { dayNumber: 1, dayOfWeek: 'Sat', title: 'Arrive Gangtok — MG Marg evening', isWorkDay: false, isExcursionDay: true, description: 'Fly into Pakyong (or drive up from Bagdogra) and settle into Gangtok. Ease in with an evening stroll down the pedestrian MG Marg, a momo dinner and an early night at altitude.', lunchNote: 'On the road / hotel', dinnerNote: 'Taste of Tibet, MG Marg', locationName: 'Gangtok', lat: 27.3389, lng: 88.6065, altitudeM: 1650 },
    { dayNumber: 2, dayOfWeek: 'Sun', title: 'Gangtok monasteries & ropeway', isWorkDay: false, isExcursionDay: true, description: 'Enchey Monastery at morning prayers, the Namgyal Institute of Tibetology and Do-Drul Chorten, then the Gangtok ropeway for a valley view. Coffee on MG Marg to plan the week.', lunchNote: 'Nimtho — Sikkimese plate', dinnerNote: 'Café Live & Loud', locationName: 'Gangtok', lat: 27.3389, lng: 88.6065, altitudeM: 1650 },
    { dayNumber: 3, dayOfWeek: 'Mon', title: 'Work day + Rumtek Monastery', isWorkDay: true, isExcursionDay: true, description: 'First work morning from a café or the hotel. Late afternoon taxi to Rumtek Monastery (24km), seat of the Karmapa — golden stupa, courtyard and ridge views back to Gangtok.', breakfastNote: 'Hotel', lunchNote: 'Baker’s Café (work here)', dinnerNote: 'Taste of Tibet', locationName: 'Rumtek', lat: 27.2887, lng: 88.5615, altitudeM: 1550 },
    { dayNumber: 4, dayOfWeek: 'Tue', title: 'Tsomgo Lake & Baba Mandir', isWorkDay: false, isExcursionDay: true, description: 'Permit-day excursion up the old Silk Route to the glacial Tsomgo (Changu) Lake at 3,750m and Baba Mandir. Yak rides, prayer flags and snow on the rim. Back to Gangtok by evening.', lunchNote: 'Tsomgo roadside dhaba', dinnerNote: 'Nimtho', locationName: 'Tsomgo Lake', lat: 27.375, lng: 88.762, altitudeM: 3753 },
    { dayNumber: 5, dayOfWeek: 'Wed', title: 'Deep work day, Gangtok', isWorkDay: true, description: 'Full focused work day from a quiet MG Marg café with Temi tea on tap. Evening walk to the Tashi or Ganesh Tok viewpoints for a Kanchenjunga silhouette at dusk.', breakfastNote: 'Hotel', lunchNote: 'The Coffee Shop, MG Marg', dinnerNote: 'Roll House + MG Marg stroll', locationName: 'Gangtok', lat: 27.3389, lng: 88.6065, altitudeM: 1650 },
    { dayNumber: 6, dayOfWeek: 'Thu', title: 'Work + drive to Pelling', isWorkDay: true, isExcursionDay: true, description: 'Half-day work, then the scenic drive west to Pelling (115km). Check into a Kanchenjunga-facing cottage; evening at the Pemayangtse Monastery viewpoint.', lunchNote: 'On the road', dinnerNote: 'Resort dining, Pelling', locationName: 'Pelling', lat: 27.3152, lng: 88.2398, altitudeM: 2150 },
    { dayNumber: 7, dayOfWeek: 'Fri', title: 'Khecheopalri Lake & Yuksom', isWorkDay: false, isExcursionDay: true, description: 'Visit the sacred Khecheopalri wish-fulfilling lake, then Yuksom — Sikkim’s first capital — and the Norbugang coronation throne. Rabdentse ruins on the way back if time allows.', lunchNote: 'Yuksom village kitchen', dinnerNote: 'Pelling', locationName: 'Yuksom', lat: 27.3722, lng: 88.2208, altitudeM: 1780 },
    { dayNumber: 8, dayOfWeek: 'Sat', title: 'Back to Gangtok + work', isWorkDay: true, isExcursionDay: true, description: 'Morning drive back east to Gangtok. Afternoon work session from the hotel. Evening shopping for Temi tea and cardamom on MG Marg.', lunchNote: 'On the road', dinnerNote: 'Dragon Wok / MG Marg', locationName: 'Gangtok', lat: 27.3389, lng: 88.6065, altitudeM: 1650 },
    { dayNumber: 9, dayOfWeek: 'Sun', title: 'Ravangla — Buddha Park & Maenam', isWorkDay: false, isExcursionDay: true, description: 'Day trip south to Ravangla for the giant Buddha statue at Tathagata Tsal and a forest walk into the Maenam sanctuary for a Teesta-valley panorama. Tea at a hillside estate on the way.', lunchNote: 'Ravangla café', dinnerNote: 'Nimtho, Gangtok', locationName: 'Ravangla', lat: 27.307, lng: 88.362, altitudeM: 2100 },
    { dayNumber: 10, dayOfWeek: 'Mon', title: 'Slow morning & farewell', isWorkDay: false, isExcursionDay: true, description: 'A relaxed final morning — last coffee on MG Marg, any remaining shopping for thangka or carpets at the handicrafts emporium, then the transfer to Pakyong or Bagdogra for departure.', lunchNote: 'Baker’s Café', dinnerNote: 'Airport / departure', locationName: 'Gangtok', lat: 27.3389, lng: 88.6065, altitudeM: 1650 },
  ],
} as const
