// src/lib/content/spiti.ts
// Curated launch content for Spiti Valley (Himachal). Seeded idempotently by
// ensureContent(). Note: Spiti is high & remote — the itinerary acclimatises.

export const SPITI = {
  stays: [
    { name: 'Sakya Abode, Kaza', type: 'HOTEL', neighbourhood: 'Kaza', pricePerNightINR: 3500, priceMonthlyINR: 70000, wifiRating: 2, hasCoworking: false, hasPowerBackup: true, viewType: 'Town & ranges', breakfastIncl: true, available: true, description: 'One of Kaza’s most comfortable stays — warm rooms, hot water and the best WiFi you’ll find in the valley (still modest).', highlights: ['Warm rooms', 'Best-effort WiFi', 'Central Kaza', 'Breakfast'] },
    { name: 'Zostel Spiti (Kaza)', type: 'HOSTEL', neighbourhood: 'Kaza', pricePerNightINR: 1200, priceMonthlyINR: 26000, wifiRating: 2, hasCoworking: true, hasPowerBackup: true, viewType: 'Spiti river & mountains', breakfastIncl: false, available: true, description: 'Backpacker hub with a sunny common room that doubles as a rough co-working space and a riverside café. Social, budget-friendly.', highlights: ['Common room', 'Budget', 'Café', 'Social'] },
    { name: 'Kibber Homestay', type: 'HOMESTAY', neighbourhood: 'Kibber', pricePerNightINR: 1500, wifiRating: 1, hasCoworking: false, hasPowerBackup: false, viewType: 'High village & valley', breakfastIncl: true, available: true, description: 'Family homestay in one of the world’s highest villages — home-cooked Spitian meals, thick blankets and total silence.', highlights: ['Home-cooked meals', 'High village', 'Authentic', 'Stargazing'] },
    { name: 'Langza Homestay', type: 'HOMESTAY', neighbourhood: 'Langza', pricePerNightINR: 1500, wifiRating: 1, hasCoworking: false, hasPowerBackup: false, viewType: 'Buddha statue & Chau Chau Kang Nilda', breakfastIncl: true, available: true, description: 'Stay under the giant Langza Buddha at 4,400m — fossil-hunting fields, prayer flags and brilliant night skies.', highlights: ['Fossils', 'Giant Buddha', 'Dark skies', 'Home-cooked'] },
    { name: 'Dhankar Homestay', type: 'HOMESTAY', neighbourhood: 'Dhankar', pricePerNightINR: 1600, wifiRating: 1, hasCoworking: false, hasPowerBackup: false, viewType: 'Spiti–Pin confluence', breakfastIncl: true, available: true, description: 'Perched below the dramatic Dhankar monastery, overlooking the Spiti–Pin river confluence. Hike to the sacred lake above.', highlights: ['Cliff monastery', 'River confluence', 'Lake hike'] },
  ],
  food: [
    { name: 'Sol Café, Kaza', type: 'CAFE', neighbourhood: 'Kaza', description: 'Sunny social-enterprise café run by Ecosphere — coffee, soups, baked goods and the valley’s best wifi-ish corner to work from.', mustOrder: ['Sea-buckthorn tea', 'Soup & bread', 'Apple cake'], wifiAvailable: true, laptopFriendly: true, avgBudgetINR: 350, openNow: true, seasonal: true, tags: ['Work-Friendly', 'Coffee', 'Cause'] },
    { name: 'Taste of Spiti, Kaza', type: 'RESTAURANT', neighbourhood: 'Kaza', description: 'Cosy spot for authentic Spitian and Tibetan food — thenthuk, momos and butter tea after a cold day out.', mustOrder: ['Thenthuk', 'Yak cheese momo', 'Butter tea'], wifiAvailable: false, laptopFriendly: false, avgBudgetINR: 400, openNow: true, seasonal: true, tags: ['Local', 'Tibetan', 'Warm'] },
    { name: 'Himalayan Café & German Bakery', type: 'BAKERY', neighbourhood: 'Kaza', description: 'Fresh bread, apple pie and strong coffee — the morning fuel stop before long drives to the high villages.', mustOrder: ['Apple pie', 'Cinnamon roll', 'Filter coffee'], wifiAvailable: false, laptopFriendly: true, avgBudgetINR: 300, openNow: true, seasonal: true, tags: ['Bakery', 'Coffee'] },
    { name: 'Café Kunzum Top', type: 'CAFE', neighbourhood: 'Kaza', description: 'Laid-back café with Spiti river views — Maggi, momos and chai, the universal mountain trio.', mustOrder: ['Veg momos', 'Maggi', 'Ginger-lemon-honey'], wifiAvailable: false, laptopFriendly: true, avgBudgetINR: 250, openNow: true, seasonal: true, tags: ['Views', 'Chill'] },
    { name: 'Komic Heights (highest café)', type: 'CAFE', neighbourhood: 'Komic', description: 'One of the world’s highest cafés at ~4,587m — basic, freezing, unforgettable. Tea with a view of forever.', mustOrder: ['Black tea', 'Maggi', 'Local barley snacks'], wifiAvailable: false, laptopFriendly: false, avgBudgetINR: 200, openNow: true, seasonal: true, tags: ['Highest', 'Bucket-list'] },
    { name: 'Pin Valley Dhaba (Mudh)', type: 'DHABA', neighbourhood: 'Mudh, Pin Valley', description: 'Simple village dhaba at the road-head of Pin Valley — hot dal, rice and rajma to refuel trekkers.', mustOrder: ['Dal chawal', 'Rajma', 'Chai'], wifiAvailable: false, laptopFriendly: false, avgBudgetINR: 250, openNow: true, seasonal: true, tags: ['Village', 'Comfort Food'] },
  ],
  treks: [
    { name: 'Langza – Komic – Hikkim walk', difficulty: 'MEDIUM', durationDays: 1, maxAltitudeM: 4587, distanceKm: 9, startPoint: 'Langza', permitRequired: false, priceINR: 1500, company: 'Kaza guides', available: true, season: 'Jun–Sep', description: 'A high-altitude village loop — fossil fields at Langza, the world’s highest motorable village Komic, and Hikkim’s highest post office. Go slow.', highlights: ['Fossils', 'Highest village', 'Highest post office', 'Big skies'] },
    { name: 'Dhankar Lake hike', difficulty: 'MEDIUM', durationDays: 1, maxAltitudeM: 4270, distanceKm: 5, startPoint: 'Dhankar', permitRequired: false, priceINR: 1200, company: 'Local guides', available: true, season: 'Jun–Sep', description: 'A steep but short climb from Dhankar monastery to a serene glacial lake — stop often to breathe at altitude.', highlights: ['Glacial lake', 'Dhankar gompa', 'Confluence views'] },
    { name: 'Pin Valley – Mudh exploration', difficulty: 'MEDIUM', durationDays: 2, maxAltitudeM: 3700, distanceKm: 16, startPoint: 'Mudh, Pin Valley', permitRequired: false, priceINR: 4500, company: 'Pin Valley guides', available: true, season: 'Jun–Sep', description: 'Wander the green-and-ochre Pin Valley National Park from Mudh village — ibex country, the gateway to the Pin-Parvati and Bhaba passes.', highlights: ['Pin Valley NP', 'Mudh village', 'Wildflowers', 'Snow leopard habitat'] },
    { name: 'Kibber – Tashigang', difficulty: 'EASY', durationDays: 1, maxAltitudeM: 4400, distanceKm: 7, startPoint: 'Kibber', permitRequired: false, priceINR: 1200, company: 'Kibber homestays', available: true, season: 'Jun–Sep', description: 'Gentle high-plateau walk from Kibber toward tiny Tashigang, past the wildlife sanctuary — a good acclimatisation day.', highlights: ['Kibber sanctuary', 'Plateau views', 'Acclimatisation'] },
  ],
  events: [
    { name: 'Losar (Spitian New Year)', type: 'FESTIVAL', location: 'Key & village monasteries', startISO: '2026-12-19', endISO: '2026-12-21', ticketRequired: false, freeEntry: true, description: 'The Tibetan-Buddhist new year — masked Chaam dances, butter lamps and feasting at Key and the village gompas. Deep winter, deeply atmospheric.', tips: 'Winter Spiti is extreme; only for the well-prepared.' },
    { name: 'Ladarcha Fair, Kaza', type: 'MARKET', location: 'Kaza', startISO: '2026-07-20', endISO: '2026-07-22', ticketRequired: false, freeEntry: true, description: 'A historic trans-Himalayan trade fair — once where Spiti, Ladakh and Tibet met to barter. Now a lively cultural market in Kaza.', tips: 'Peak summer; book Kaza stays early.' },
    { name: 'Key Monastery Chaam', type: 'MONASTERY', location: 'Key Monastery', startISO: '2026-08-15', endISO: '2026-08-16', ticketRequired: false, freeEntry: true, description: 'Masked Chaam dances at Spiti’s largest and most photogenic monastery, stacked on its hill above the river.', tips: 'Arrive early; mornings are best for photos and light.' },
    { name: 'Pin Valley Festival', type: 'CULTURAL', location: 'Gungri / Kungri, Pin Valley', startISO: '2026-07-25', endISO: '2026-07-26', ticketRequired: false, freeEntry: true, description: 'Nyingma-tradition festival at Kungri monastery in Pin Valley — devil dances, local music and village hospitality.', tips: 'Combine with a Pin Valley homestay night.' },
  ],
  transport: [
    { type: 'SHARED_JEEP', destination: 'Manali → Kaza', distanceKm: 200, rateINR: 4500, rateType: 'one-way', permitRequired: false, permitTypes: [], durationHours: 10, notes: 'Via Kunzum La (4,590m). Open ~Jun–Oct only; long, rough, spectacular.', available: true },
    { type: 'SHARED_JEEP', destination: 'Shimla → Kaza', distanceKm: 420, rateINR: 6000, rateType: '2-day', permitRequired: false, permitTypes: [], durationHours: 16, notes: 'All-season route via Kinnaur; usually split over two days (overnight Kalpa/Nako).', available: true },
    { type: 'TAXI', destination: 'Kaza → Key + Kibber', distanceKm: 35, rateINR: 2500, rateType: '1-day', permitRequired: false, permitTypes: [], durationHours: 3, notes: 'Half-day loop to the monastery and high villages.', available: true },
    { type: 'TAXI', destination: 'Kaza → Langza-Komic-Hikkim', distanceKm: 45, rateINR: 3000, rateType: '1-day', permitRequired: false, permitTypes: [], durationHours: 4, notes: 'The classic high-village circuit; go slow for altitude.', available: true },
    { type: 'TAXI', destination: 'Kaza → Dhankar + Pin Valley', distanceKm: 70, rateINR: 3800, rateType: '1-day', permitRequired: false, permitTypes: [], durationHours: 5, notes: 'Dhankar gompa, then into Pin Valley NP toward Mudh.', available: true },
  ],
  shop: [
    { name: 'Sea-buckthorn juice & jam', area: 'Kaza', category: 'Food', estPriceINR: 350, whereToBuy: 'Ecosphere / Sol Café, Kaza', priority: 'must', notes: 'Tart high-altitude superfruit; supports local women’s collectives.' },
    { name: 'Spiti dried green peas', area: 'Kaza', category: 'Food', estPriceINR: 200, whereToBuy: 'Kaza market', priority: 'nice', notes: 'The valley’s cash crop — sweet and floury.' },
    { name: 'Handspun yak-wool woollens', area: 'Kibber', category: 'Textiles', estPriceINR: 1500, whereToBuy: 'Village co-ops', priority: 'nice', notes: 'Socks, caps and shawls — warm and ethically local.' },
    { name: 'Thangka / prayer flags', area: 'Kaza', category: 'Spiritual', estPriceINR: 800, whereToBuy: 'Monastery shops', priority: 'nice', notes: 'Small thangkas and lungta flag strings.' },
    { name: 'Spiti apricots & seabuckthorn tea', area: 'Tabo', category: 'Food', estPriceINR: 300, whereToBuy: 'Tabo / roadside stalls', priority: 'nice', notes: 'Dried fruit and herbal teas from the lower valley.' },
    { name: 'Local barley (chhang/ tsampa) packs', area: 'Kaza', category: 'Food', estPriceINR: 250, whereToBuy: 'Kaza market', priority: 'maybe', notes: 'Roasted barley flour — the staple grain of the valley.' },
  ],
  itinerary: [
    { dayNumber: 1, dayOfWeek: 'Sat', title: 'Arrive Kaza — rest & acclimatise', isWorkDay: false, description: 'Reach Kaza (3,650m). Do almost nothing — hydrate, walk the small town slowly, sleep early. Altitude is real here.', lunchNote: 'Taste of Spiti', dinnerNote: 'Sakya Abode — early night', locationName: 'Kaza', lat: 32.2264, lng: 78.0716, altitudeM: 3650 },
    { dayNumber: 2, dayOfWeek: 'Sun', title: 'Easy Kaza day + Sol Café', isWorkDay: false, isExcursionDay: true, description: 'Gentle acclimatisation — Kaza monastery, the market and a long lazy session at Sol Café. Keep exertion low.', lunchNote: 'Sol Café', dinnerNote: 'Café Kunzum Top', locationName: 'Kaza', lat: 32.2264, lng: 78.0716, altitudeM: 3650 },
    { dayNumber: 3, dayOfWeek: 'Mon', title: 'Work day, Kaza', isWorkDay: true, description: 'First work morning from Sol Café (best connectivity in the valley — manage expectations). Easy evening stroll by the river.', breakfastNote: 'German Bakery', lunchNote: 'Sol Café (work here)', dinnerNote: 'Taste of Spiti', locationName: 'Kaza', lat: 32.2264, lng: 78.0716, altitudeM: 3650 },
    { dayNumber: 4, dayOfWeek: 'Tue', title: 'Key Monastery & Kibber', isWorkDay: false, isExcursionDay: true, description: 'Half-day loop to the iconic Key Monastery, then up to Kibber, one of the world’s highest villages. Back to Kaza to sleep low.', lunchNote: 'Kibber homestay', dinnerNote: 'Kaza', locationName: 'Key Monastery', lat: 32.298, lng: 78.012, altitudeM: 4166 },
    { dayNumber: 5, dayOfWeek: 'Wed', title: 'Work day, Kaza', isWorkDay: true, description: 'Focused work day in town. Stock up at the market; rest for the high-village circuit tomorrow.', breakfastNote: 'Sakya Abode', lunchNote: 'Sol Café', dinnerNote: 'Café Kunzum Top', locationName: 'Kaza', lat: 32.2264, lng: 78.0716, altitudeM: 3650 },
    { dayNumber: 6, dayOfWeek: 'Thu', title: 'Langza • Hikkim • Komic', isWorkDay: false, isExcursionDay: true, description: 'The high-village classic — fossils under the Langza Buddha, post a card from Hikkim (world’s highest post office), tea at Komic (~4,587m).', lunchNote: 'Komic Heights café', dinnerNote: 'Langza homestay', locationName: 'Langza', lat: 32.27, lng: 78.07, altitudeM: 4400 },
    { dayNumber: 7, dayOfWeek: 'Fri', title: 'Dhankar monastery & lake', isWorkDay: false, isTrekDay: true, description: 'Drive to the cliff-clinging Dhankar gompa over the Spiti–Pin confluence, then hike up to the still Dhankar Lake. Overnight at Dhankar.', lunchNote: 'Dhankar homestay', dinnerNote: 'Dhankar homestay', locationName: 'Dhankar', lat: 32.083, lng: 78.217, altitudeM: 3894 },
    { dayNumber: 8, dayOfWeek: 'Sat', title: 'Pin Valley & Mudh', isWorkDay: false, isExcursionDay: true, description: 'Into the green Pin Valley National Park to Mudh village — ibex country and trailheads. Return toward Kaza by evening.', lunchNote: 'Pin Valley dhaba (Mudh)', dinnerNote: 'Kaza', locationName: 'Pin Valley (Mudh)', lat: 31.94, lng: 78.0, altitudeM: 3650 },
    { dayNumber: 9, dayOfWeek: 'Sun', title: 'Work + Tabo monastery', isWorkDay: true, isExcursionDay: true, description: 'Work morning, then drive down-valley to the 1,000-year-old Tabo monastery — the “Ajanta of the Himalayas”. Lower altitude, gentler night.', lunchNote: 'Tabo café', dinnerNote: 'Kaza', locationName: 'Kaza', lat: 32.2264, lng: 78.0716, altitudeM: 3650 },
    { dayNumber: 10, dayOfWeek: 'Mon', title: 'Chandratal or departure', isWorkDay: false, isExcursionDay: true, description: 'If the Kunzum road is open, a dawn run to the cobalt Chandratal lake; otherwise a slow last morning and shopping for sea-buckthorn before departure.', lunchNote: 'Packed lunch', dinnerNote: 'Departure', locationName: 'Chandratal', lat: 32.479, lng: 77.619, altitudeM: 4300 },
  ],
} as const
